# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: derh4nnes/pipeline-behat:latest
clone:
  depth: full

pipelines:
  default:
    - step:
        name: Build and test
        caches:
          - composer
        script:
          - cd ..
          - mkdir config_replace/
          - mv build/* config_replace/
          - mv config_replace/ build/
          - cd build
          - composer create-project drupal-composer/drupal-project:8.x-dev drupal --stability dev --no-interaction
          - mv config_replace drupal/web/modules/
          - (cd drupal/web/modules/config_replace/tests/ && ../../../../vendor/bin/phpunit)
    - step:
        name: Deploy
        script:
          - git remote add d.o jepSter@git.drupal.org:project/config_replace.git
          - git config --global push.default simple
          - git config --global user.name "Peter Majmesku"
          - git push -u d.o
          - git push --tags
