# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: ubuntu:17.10
clone:
  depth: full

pipelines:
  default:
    - step:
        name: Build and test
        caches:
          - composer
        script:
          - apt-get update
          - apt-get install -y wget bzip2 curl sqlite3 screen
          - curl -sL https://deb.nodesource.com/setup_8.x -o nodesource_setup.sh
          - apt-get update
          - apt-get install -y nodejs npm
          - curl -sL https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh -o install_nvm.sh
          - bash install_nvm.sh
          - source ~/.profile
          - nvm install 8.11.2
          - (cd /tmp && wget -qO- https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 | tar jx && chmod +x /tmp/phantomjs-2.1.1-linux-x86_64/bin/phantomjs)
          - apt-get install -y unzip git curl php php-cli php-gd php-curl php7.1-sqlite
          - apt-get install -y php-dom php-json php-common php-mbstring
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - export PATH="$HOME/.composer/vendor/bin:$PATH"
          - composer global require drush/drush:^9
          - cd ..
          - mkdir permissions_by_term/
          - mv build/* permissions_by_term/
          - mv permissions_by_term/ build/
          - cd build
          - composer create-project drupal-composer/drupal-project:8.x-dev drupal --stability dev --no-interaction
          - mv permissions_by_term drupal/web/modules/
          - (cd drupal/web/modules/permissions_by_term/tests/ && ../../../../vendor/bin/phpunit)
          - (cd drupal/web/modules/permissions_by_term/js/ && npm install && npm run bat)
          - (cd drupal/web && drush si standard --db-url=sqlite://sites/default/files/db.sqlite -y && drush en permissions_by_term -y)
          - (cd drupal && composer require behat/behat:^3.0 behat/mink:~1.7 behat/mink-goutte-driver:~1.2 behat/mink-extension:^2.2 drupal/drupal-extension:^3.2 --dev)
          - (cd drupal && cp web/modules/permissions_by_term/tests/src/Behat/composer-require-namespace.php . && php composer-require-namespace.php && composer dump-autoload)
          - (cd drupal && cat composer.json)
          - screen -dmS phantomjs /tmp/phantomjs-2.1.1-linux-x86_64/bin/phantomjs --webdriver=4444
          - screen -dmS php-server php -S localhost:8000 -t ./drupal/web
          - php -S localhost:8000 -t ./drupal/web &
          - (cd drupal/web && cp modules/permissions_by_term/tests/src/Behat/behat.yml.dist behat.yml && ../vendor/bin/behat)
      services:
        - testing
    - step:
        name: Deploy
        script:
          - apt-get update && apt-get install -y unzip git
          - git remote add d.o jepSter@git.drupal.org:project/permissions_by_term.git
          - git config --global push.default simple
          - git config --global user.name "Peter Majmesku"
          - git push -u d.o
          - git push --tags

definitions:
  services:
    testing:
      image: darksolar/selenium-chrome-headless
