services:
  config_replace.config_replacer:
    class: Drupal\config_replace\ConfigReplacer
    arguments: ['@config.factory', '@module_handler', '@logger.channel.config_replace', '@?language.config_factory_override']
  logger.channel.config_replace:
    class: Drupal\Core\Logger\LoggerChannel
    factory: logger.factory:get
    arguments: ['config_replace']
