name: Configuration Replace
type: module
description: Replaces existing configuration on module installation via using a "rewrite" folder in the config directory.
core_version_requirement: '^8 || ^9'
package: Configuration
